"""Initial

Revision ID: 691de30306a3
Revises: 
Create Date: 2024-01-28 10:47:44.725235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "691de30306a3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchanger",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cource",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trade_pair", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanger.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cource")
    op.drop_table("exchanger")
    # ### end Alembic commands ###
